version: "3.2"

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: pupe
      POSTGRES_USER: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
  pupe-http:
    image: pupe:0.1.0-SNAPSHOT
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    links:
      - postgresql:postgreshost
  pupe-ui:
    image: pupe-ui
    build: .
    ports:
      - "3000:3000"
