version: "3.2"

services:
  web:
    image: pupe:0.1.0-SNAPSHOT
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  ui:
    image: pupe-ui
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_DB:'pupe'
    volumes:
        - database:/var/lib/postgresql/data
volumes:
  database:
